### ISSUE TITLE
add PHYLIP reader and sniffer

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1006]
It would be useful to support reading and sniffing PHYLIP files. We already support writing an alignment in PHYLIP format.

**Comment by patena** [comment]
I'll try doing this.

**Comment by patena** [comment]
Question: In order to be validated, the file has to be read completely, since the header specifies the number of sequences. However, should I still implement a sniffer that ignores that condition and only reads the header and first sequence instead of reading the whole file?

**Comment by ebolyen** [comment]
Yes, the sniffer is considered to be an imperfect "best-effort" mechanism. They aren't really meant to validate the file so much as positively identify it.

**Comment by jhcepas** [comment]
ete's code for read and write parsing: https://github.com/jhcepas/ete/blob/master/ete2/parser/phylip.py

**Comment by patena** [comment]
Implemented basic reader/sniffer - see #1011 

@jhcepas Thanks for the code! I'll probably try including that in my next version (the current one I wrote before seeing your code only does the strict sequential format)

**Comment by patena** [comment]
If I wanted to implement the interleaved format and the relaxed option, how should the sniffer and reader deal with that?  Make a separate format for each?  Just sniff for Phylip in general (pretty easy)? Make the reader take arguments specifying the type, or try to figure it out (or have both as an option)?

A few other format issues:
* the code from ETE implements skipping blank lines and comments (starting with #) - do we want that, or should we stick with the strict version?
* theoretically the sequential format can have multiple lines per sequence - currently not implemented. Do we want that? (Could be done by checking after each line whether the expected seq length has been reached... This format is really terrible.)
* According to the [original specification](http://evolution.genetics.washington.edu/phylip/doc/sequence.html) "a portion of a sequence like this: ``300 AAGCGTGAAC GTTGTACTAA TRCAG`` is perfectly legal" because "digits and blanks will be ignored, the sequence being taken as starting at the first base symbol". Do we want to implement ignoring all digits just like we ignore spaces?

Or we could just stick with the current strict sequential one-line format and see if anyone actually wants the other ones...

**Comment by averagehat** [comment]
fixed link that jhcepas posted https://github.com/jhcepas/ete/blob/04e709b4f942a1e05939d335a5e11cc0c63f455a/ete3/parser/phylip.py

**Comment by ebolyen** [comment]
@patena Aren't bioinformatics formats fun? I say we stick with strict for now and if someone posts an issue, we can deal with it then. @jairideout thoughts?

**Comment by jhcepas** [comment]
ETE's parser is also able to warn (or even rename) about duplicated names. Not a restriction in the FASTA and PHYLIP format, but *extremely* useful IMO. Sticking to the strict specification is just right, but things like allowing #lines are not explicitly forbidden and could be very useful from the user perspective. It is not uncommon to have commented lines in the header of FASTA files, for instance. Being too strict will force end users to fix problems in the output files from third party software. My preference is usually: read as much as possible without breaking basic formatting, and warn about weird stuff.

**Comment by jairideout** [comment]
> @patena Aren't bioinformatics formats fun? I say we stick with strict for now and if someone posts an issue, we can deal with it then. @jairideout thoughts?

Sounds like a good plan. Thanks @patena for adding this functionality, and thanks @jhcepas for your code and input!
