### ISSUE TITLE
Remove duplication between setup.py and requirements.txt files

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio#1049]
We're currently maintaining 2 separate lists of requirements, one in `setup.py`, and the other in `ci/pip_requirements.txt` and `ci/conda_requirements.txt`. Most recently I came across this issue when `make test` failed because I didn't have `check-manifest` installed. This happened even after doing `pip install -e .` for scikit-bio. This was fixed by running `pip install -r ci/pip_requirements.txt`, since `check-manifest` is listed in that file.

I think a first step in fixing this would be to use `ci/pip_requirements.txt` in `setup.py`. The tricky part is that we currently can't rely on users using conda, so we can't simply run `conda install --file ci/conda_requirements.txt` from `setup.py`. So we might still need to introduce some duplication between `ci/pip_requirements.txt` and `ci/conda_requirements.txt`. The idea being if the user is using conda they can run `conda install --file ci/conda_requirements.txt` before installing scikit-bio in order to speed up the installation by harnessing conda's binary packages.

**Comment by jairideout** [comment]
@anderspitman `pip install -e .` didn't install `check-manifest` because it is an optional dependency that is only necessary for scikit-bio developers to have installed.

I agree the duplication is less than ideal but I think the `ci` requirements files are distinct from the requirements listed in setup.py. The `ci` requirements files list *all* dependencies (required and optional) necessary to fully test scikit-bio (building docs, various testing/linting tools, etc.). They are intended for scikit-bio devs and travis-ci but not for end users.

For end users, the requirements in setup.py should be sufficient to get a working scikit-bio installation via `pip` and `python setup.py install`. For conda users, `conda install scikit-bio` should also just work.

**Comment by jairideout** [comment]
Also see [this blog post](https://caremad.io/2013/07/setup-vs-requirement/) for a great explanation of the differences between setup.py and requirements files, and why some duplication is necessary.

**Comment by anderspitman** [comment]
:+1: definitely more semantics here than I realized!
