### ISSUE TITLE
Deprecate `nondegenerate_chars` in favor of a better name.

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1071]
Using `nondegenerate` was probably a mistake. It is hard to talk about (I know I have mixed myself up a couple of times) and it almost implies the inverse of `degenerate` which isn't really the intention. Fortunately, it shouldn't be too painful to deprecate and gives us a chance to exercise that process.

`standard` might be a better description. So to kick off the conversation, I propose we deprecate the following:

`nondegenerate_chars` -> `standard_chars`
`has_nondegenerates()` -> `has_standards()`
`nondegenerates()` -> `standards()`

The only thing I'm not too jazzed about is how awkward `standard` is when plural. `has_standards()` is a particularly amusing demonstration of this. 

Does anyone have a better name to describe the "normal" bases of a sequence?

**Comment by ebolyen** [comment]
For context, @jairideout and I were discussing this offline last Friday.

**Comment by jairideout** [comment]
How about describing the nondegenerate characters as "regular"? "standard" implies the standard IUPAC characters, while this API may apply to an entirely different alphabet in the future.

So the API would become:

- `nondegenerate_chars` -> `regular_chars`
- `has_nondegenerates()` -> `has_regulars()`
- `nondegenerates()` -> `regulars()`

**Comment by ebolyen** [comment]
:+1:

**Comment by gregcaporaso** [comment]
This came up in discussion today and we think the terms we should use are *definite* and *degenerate*, with *definite* replacing *nondegenerate*. 

We landed on *definite* based on the definition: [*clearly stated or decided; not vague or doubtful*](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=define+definite). While *indefinite* is probably a more relevant term than *degenerate*, we're not going to replace *degenerate* with *indefinite*, since *degenerate* is widely understood in this context. We will however document degenerate characters as being *indefinite*.

**Comment by jairideout** [comment]
@anderspitman are you interested in working on this? It'd be a good next step now that we have `GrammaredSequence`.

**Comment by anderspitman** [comment]
@jairideout since we're going to be using our deprecation process for this, do I need to start by making a PR that marks all the nondegenerate stuff as deprecated as of our next release? I could also change the names of things but keep the old names as aliases that simply call the new names and mark the aliases as deprecated.

**Comment by jairideout** [comment]
That sounds good, you can do this all in a single PR

**Comment by anderspitman** [comment]
OK. Also, for the tests, should I change all of them to use `definite`? This would introduce a small amount of surface area for bugs, but I don't think the risk is very high. The safest solution would be to duplicate at the tests for `nondegenerate` and `definite` then remove the old tests when we completely get rid of `nondegenerate` in 2 releases.

**Comment by jairideout** [comment]
for safety I'd duplicate the tests and then remove them when the deprecated names are removed

**Comment by anderspitman** [comment]
:+1:
