### ISSUE TITLE
[BUG] Writing Alignment causes issues with positional metadata

### ISSUE THREAD

**Issue by dansondergaard** [biocore/scikit-bio#1133]
I just hit upon a weird bug. To reproduce,

```bash
$ conda create -n alignment-bug python=2.7 scikit-bio=0.4.0
$ source activate alignment-bug
```

Then run the following script:

```python
import skbio as sk

seqs = [sk.DNA('ACGT', metadata={'id': 'foo'}),
		sk.DNA('AG-T', metadata={'id': 'bar'})]

aln = sk.Alignment(seqs)
print aln.position_counters()
aln.write('test.fa', format='fasta')
print aln.position_counters()
```

This will print (before the call to `write()`):

```python
[Counter({'A': 2}), Counter({'C': 1, 'G': 1}), Counter({'-': 1, 'G': 1}), Counter({'T': 2})]

```

and then (after the call to `write()`):

```python-traceback
Traceback (most recent call last):
  File "test_bug.py", line 11, in <module>
    print aln.position_counters()
  File "/home/das/anaconda/lib/python2.7/site-packages/skbio/alignment/_alignment.py", line 1227, in position_counters
    return [Counter(p) for p in self.iter_positions(constructor=str)]
  File "/home/das/anaconda/lib/python2.7/site-packages/skbio/alignment/_alignment.py", line 1041, in iter_positions
    position = [constructor(seq[i]) for seq in self]
  File "/home/das/anaconda/lib/python2.7/site-packages/skbio/sequence/_sequence.py", line 880, in __getitem__
    return self._to(sequence=seq, positional_metadata=positional_metadata)
  File "/home/das/anaconda/lib/python2.7/site-packages/skbio/sequence/_sequence.py", line 1969, in _to
    positional_metadata=positional_metadata)
  File "/home/das/anaconda/lib/python2.7/site-packages/skbio/sequence/_iupac_sequence.py", line 586, in _constructor
    return self.__class__(validate=False, lowercase=False, **kwargs)
  File "/home/das/anaconda/lib/python2.7/site-packages/skbio/sequence/_iupac_sequence.py", line 172, in __init__
    sequence, metadata, positional_metadata)
  File "/home/das/anaconda/lib/python2.7/site-packages/skbio/sequence/_sequence.py", line 585, in __init__
    self.positional_metadata = positional_metadata
  File "/home/das/anaconda/lib/python2.7/site-packages/skbio/sequence/_sequence.py", line 509, in positional_metadata
    (num_rows, len(self)))
ValueError: Number of positional metadata values (4) must match the number of characters in the sequence (1).
```

Note: Running the same code with version 0.2.3 works perfectly.

I realize that this may not be a concern since `TabularMSA` is taking over anyway. The only way I found to avoid the exception so far is to not write the alignment.

Cheers,
Dan

**Comment by ebolyen** [comment]
Thanks @dansondergaard this is a really weird one! One thing that caught my eye was the use of `StringIO.StringIO` instead of `io.StringIO`, but that doesn't seem to be the problem here. 

If the problem is in `Alignment` then it probably isn't a blocker, but we should investigate to figure out why this is happening. Worst case, this is some strange behaviour from the sequence classes, in which case this is a blocking bug.

Until we can figure out why, let's assume the worst.

**Comment by ebolyen** [comment]
Tracked down the line that is causing it:
https://github.com/biocore/scikit-bio/blob/master/skbio/io/format/_base.py#L185

The check for positional metadata will end up creating it (but it will be empty). What is disconcerting is that the code should still work regardless of that fact.

**Comment by ebolyen** [comment]
It is a problem with `Sequence`:
```python
import skbio 

seq = skbio.DNA('ACGT', metadata={'id': 'foo'})
_ = seq.positional_metadata
seq[0]
```
also causes this error.

**Comment by ebolyen** [comment]
Got it! The logical error is that `Sequence.__getitem__` checks `has_positional_metadata` which is False when it is both unset, *and empty*. By asking for `positional_metadata` we create an empty `DataFrame` on the object for the user to use. Because this is falsey, `getitem` doesn't try to pass on the sliced `positional_metadata` which means in the `_to` call existing positional metadata (with the wrong size) is inherited from the instance.

**Comment by Jorge-C** [comment]
Nice sleuthing!

**Comment by dansondergaard** [comment]
@ebolyen The `StringIO` should have been removed, that was my mistake. It's not used at all.

Really nice and quick debugging!
