### ISSUE TITLE
Error in TreeNode.read documentation

### ISSUE THREAD

**Issue by geronimp** [biocore/scikit-bio#1244]
Hi there,

The documentation describing the method of importing a tree is no longer correct in this tutorial, and possibly elsewhere:
http://scikit-bio.org/docs/latest/tree.html

**In documentation**
```
>>> TreeNode.read(StringIO("((A, B)C, D)root;"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: initial_value must be unicode or None, not str
```
**Proposed fix**
```
>>> TreeNode.read(StringIO(u"((A, B)C, D)root;"))
<TreeNode, name: root, internal node count: 1, tips count: 3>
```

Thanks,
Joel

**Comment by ebolyen** [comment]
Hi @geronimp! Our docs are actually written for Python 3. I would highly recommend switching if that is possible for you. It is a far superior language as far as file-handling is concerned. scikit-bio will eventually [completely transition to 3](https://github.com/biocore/scikit-bio-rfcs/blob/master/active/002-py3-only.md). 

Please feel free to give us a ping if there's anything else!

**Comment by wwood** [comment]
Hi @ebolyen, just to be clear here this isn't just a documentation thing, but skbio changes somewhere along the line between 0.2.2 and 0.4.0 broke our (test) code, arguably making this a regression.

Don't really want to migrate to python 3, but I guess we are left with little choice since it seems the 0.4 branch won't be maintained.

Ah progress.. thanks for the clear response though.

**Comment by jairideout** [comment]
@wwood can you please create a new issue with a code example illustrating the problem? This issue was about scikit-bio's doctests now being written in Python 3.

We're planning a minor bugfix release (0.4.2) which will be Python 2/3 compatible. This release should go live in the next couple of weeks. After that we are planning to support Python 3 only for future releases.

**Comment by wwood** [comment]
OK, thanks. That'll be #1257
