### ISSUE TITLE
Implement ufunc dispatch overriding for Sequence objects

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1251]
This would be the best solution to #1250.

Then any scipy/numpy ufunc would work quickly on Sequence objects. At this time I think `scipy.spatial.distance.hamming` is the only real use case, but there may be others.

[This document](http://docs.scipy.org/doc/numpy-1.10.0/reference/arrays.classes.html) targets how to subclass ndarray, but also describes how to manage ufunc dispatch correctly (without necessarily subclassing).

**Comment by jairideout** [comment]
I ended up implementing the [numpy array interface](http://docs.scipy.org/doc/numpy/reference/arrays.interface.html) so that a scikit-bio `Sequence` object converts to an `ndarray` of characters (same as calling `.values`) when called with `np.asarray`/`np.array`. This "conversion" actually just shares the underlying data buffer with numpy, so no extra copy is made. We get a nice error if a ufunc doesn't understand a character vector:

```python
In [1]: import numpy as np

In [2]: from skbio import Sequence

In [3]: seq = Sequence('abc123')

In [4]: chars = np.asarray(seq)

In [5]: chars
Out[5]:
array([b'a', b'b', b'c', b'1', b'2', b'3'],
      dtype='|S1')

In [6]: chars - chars
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-5ab57032b8af> in <module>()
----> 1 chars - chars

TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('S1') dtype('S1') dtype('S1')
```
