### ISSUE TITLE
TreeNode.read and unicode

### ISSUE THREAD

**Issue by wwood** [biocore/scikit-bio#1257]
On python 2.7, this happens
```
>>> TreeNode.read(StringIO("((A, B)C, D)root;"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: initial_value must be unicode or None, not str
```
Can be worked around like so
```
>>> TreeNode.read(StringIO(u"((A, B)C, D)root;"))
<TreeNode, name: root, internal node count: 1, tips count: 3>
```
See also #1244 

Thanks.

**Comment by jairideout** [comment]
This is intended behavior, though we should have noted this backwards-incompatible change in the changelog when transitioning to 0.4.0, sorry for the inconvenience.

As of 0.4.0, scikit-bio's I/O system supports [these input types](http://scikit-bio.org/docs/0.4.0/generated/generated/skbio.io.util.open.html#skbio.io.util.open). This includes `io.StringIO`, which requires unicode input. This is why you need to prefix the string with `u` in Python 2.7 (our doctests are written in Python 3, which does not require the `u` prefix).

**Comment by wwood** [comment]
Thanks for the response.

>This includes `io.StringIO`, which requires unicode input.

As I understand (and I'm certainly no python afficionado), this is untrue: it is just in python3 all strings are unicode by default. This is an issue with skbio, not io.StringIO.

But anyway, in our case we can just prepend u to all the strings to make them unicode and be done with this.

**Comment by jairideout** [comment]
> As I understand (and I'm certainly no python afficionado), this is untrue: it is just in python3 all strings are unicode by default. This is an issue with skbio, not io.StringIO.

This is not an issue with scikit-bio. `io.StringIO` requires unicode input. In Python 3, you are correct that string literals are unicode by default, which is why your code works in Python 3. In Python 2, string literals are `bytes`/`str` by default unless prepended with `u`.

Trying to pass `bytes` as input in Python 3 raises the same error, independent of scikit-bio:

```python
In [1]: import io

In [2]: io.StringIO(b"foo")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-7f0d6cfe919a> in <module>()
----> 1 io.StringIO(b"foo")

TypeError: initial_value must be str or None, not bytes
```

Likewise, we see a similar error in Python 2 when passing `bytes` (which is the same as `str` in Python 2):

```python
In [1]: import io

In [2]: io.StringIO("foo")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-97c93870314b> in <module>()
----> 1 io.StringIO("foo")

TypeError: initial_value must be unicode or None, not str
```

**Comment by ebolyen** [comment]
@jairideout is right about how Python 2.7/3 interact with `StringIO`. I'd like to mention some of the reasons this issue exists at all:

One of the real design reasons for `skbio.io` to behave in this way is that `StringIO.StringIO`**** expects C strings (ASCII, null-terminated). This is actually a really broken way to think about textual data. Furthermore given the ability for `skbio.io` to simultaneously infer the given input is a URL, download it, identify that it is gzipped, unzip it, and then read it given an arbitrary user-specified encoding while testing the contents to identify the actual file format requires a huge amount of composition and nesting of these filehandles. This is especially true if the io registry has to go in ice-cold and isn't sure if a file is a binary format or a text one (think hdf5 vs csv) the former doesn't even have an encoding! (or you could consider the encoding to be hdf5, but even hdf5 has encodings within itself for text).

**** There are two of these in Python 2.7 (`io.StringIO` and `StringIO.StringIO`) and that may be the cause of some of the confusion.

Old Python file-objects while also being completely oblivious to the non-English speaking world, do not compose at all. The `io` module introduced to the standard library in 2.6 became the actual `open` and standard file-objects in 3.0. It is also built out of composable file-objects (in fact it looks a lot like Java file buffers). This is important because at different points in the process, scikit-bio may be dealing with raw binary data which could be textual, data that is actually binary, and data that is superficially binary and is only compressed textual (or maybe binary) data. None of these distinctions are really possible in the old file object model, where there is no such thing as encoding and the final representation stops at a c-style string. Unfortunately these are also distinctions that many (including myself) don't often think about. I suspect this is the real reason that `io.StringIO` will not accept a `byte` string, it could assume ASCII like everyone already was, but the just propagates the same logical flaws which can hide bugs. 

The important take-away is that text-data (`str`) in Python 3 is encoding agnostic, and so a "correct" `StringIO` filehandle should also be encoding agnostic. While in Python 2, text-data is `unicode` while `str` is an ASCII C-string and the only way to interact with a file in the textual way is to use the `io` subpackage.

This entire mess is also a huge motivation for moving to Python 3 only as maintaining compatible code is actually really hard if you want to do it right.
