### ISSUE TITLE
Not available at python2.7?

### ISSUE THREAD

**Issue by kyu999** [biocore/scikit-bio#1295]
I am new to this library, and tried to install at python2.7.
But, pip install failed.
```
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

**Comment by kyu999** [comment]
Of course, python is installed.

**Comment by ebolyen** [comment]
Hey @kyu999, the issue is with Matplotlib (from the error it looks like you are on a Mac?).

 As a general rule: Python packaging is a total mess/nightmare. To mitigate this I would recommend using either `VirtualEnv`, or `conda`. `conda` is pretty nice because it also acts as a distribution manager in addition to a Python sandbox.

**Comment by ebolyen** [comment]
Also, we are going to be dropping support for Python 2.7 very soon, so switch to 3 if possible (once again, `conda`/`VirtualEnv` can do this for you.

**Comment by kyu999** [comment]
@ebolyen Thanks for your help!
