### ISSUE TITLE
Stockholm I/O: invitation for input on dealing with reference tags

### ISSUE THREAD

**Issue by Kleptobismol** [biocore/scikit-bio#1347]
Thanks @squirrelo for bringing this to my attention. In Stockholm, tree tags are handled differently than normal tags, as described [here](http://scikit-bio.org/docs/latest/generated/skbio.io.format.stockholm.html#module-skbio.io.format.stockholm). This is the only tag type that has a different rule associated with it, or so I thought. There is another type of tag; reference, which appears to have its own rules as well. @jairideout and I have both combed the web as much as we can to try to find these rules, but as there isn't very much information on Stockholm already, we couldn't find any info on these tags, especially how this metadata should be handled. I am opening this for discussion for any input regarding how we should store this metadata. 

This is the example file's GF lines:
```
#=GF RN   [1]
#=GF RM   10094622
#=GF RT   The S box regulon: a new global transcription termination control system
#=GF RT   for methionine and cysteine biosynthesis genes in gram-positive bacteria.
#=GF RA   Grundy FJ, Henkin TM
#=GF RL   Mol Microbiol 1998;30:737-749.
#=GF RN   [2]
#=GF RM   12910260
#=GF RT   An mRNA structure that controls gene expression by binding
#=GF RT   S-adenosylmethionine.
#=GF RA   Winkler WC, Nahvi A, Sudarsan N, Barrick JE, Breaker RR
#=GF RL   Nat Struct Biol 2003;10:701-707.
#=GF RN   [3]
#=GF RM   12702767
#=GF RT   The riboswitch-mediated control of sulfur metabolism in bacteria.
#=GF RA   Epshtein V, Mironov AS, Nudler E
#=GF RL   Proc Natl Acad Sci U S A 2003;100:5052-5056.
#=GF RN   [4]
#=GF RM   15215334
#=GF RT   Comparative genomics of the methionine metabolism in Gram-positive
#=GF RT   bacteria: a variety of regulatory systems.
#=GF RA   Rodionov DA, Vitreschak AG, Mironov AA, Gelfand MS
#=GF RL   Nucleic Acids Res 2004;32:3340-3353.
#=GF RN   [5]
#=GF RM   16810258
#=GF RT   Structure of the S-adenosylmethionine riboswitch regulatory mRNA element.
#=GF RA   Montange RK, Batey RT
#=GF RL   Nature. 2006;441:1172-1175.
```
According to the [Wikipedia article](https://en.wikipedia.org/wiki/Stockholm_format), this is what all the reference tags mean:
``RN`` -- **R**eference **N**umber
``RM`` -- **R**eference **M**edline
``RT`` -- **R**eference **T**itle
``RA`` -- **R**eference **A**uthor
``RL`` -- **R**eference **L**ocation
``RC`` -- **R**eference **C**omment

So it appears every reference has to be preceded by a ``RN`` tag. Other than that, it seems the order after ``RN`` is ``RM``, ``RT``, ``RA``, ``RL``, but nothing is certain as there is no documentation on these tags, besides what they mean. 

Here's what it looks like right now if a user tries to read this file into a TabularMSA:
```python
>>> from skbio import TabularMSA, RNA
>>> with open('Stockholm.txt', 'r') as fh:
...     msa = TabularMSA.read(fh, constructor=RNA)
>>> msa
```
```
TabularMSA[RNA]
-----------------------------------------------------------------------
Metadata:
    'AC': 'RF00162'
    'AU': 'Griffiths-Jones SR, Gardner PP'
    'BM': 'cmbuild -F CM SEED'
    'CB': 'cmcalibrate --mpi CM'
    'CC': <class 'str'>
    'DE': 'SAM riboswitch (S box leader)'
    'DR': 'SO; 0000035; riboswitch;'
    'GA': '44.00'
    'ID': 'SAM'
    'NC': '43.90'
    'PI': 'S_box'
    'RA': <class 'str'>
    'RL': <class 'str'>
    'RM': '10094622 12910260 12702767 15215334 16810258'
    'RN': '[1] [2] [3] [4] [5]'
    'RT': <class 'str'>
    'SE': 'Grundy F, Henkin T, PMID:10094622'
    'SM': 'cmsearch --cpu 4 --verbose --nohmmonly -E 1000 -Z
           549862.597050 CM SEQDB'
    'SQ': '433'
    'SS': 'Published; PMID:10094622'
    'TC': '44.00'
    'TP': 'Cis-reg; riboswitch;'
    'WK': 'SAM_riboswitch_(S_box_leader)'
Positional metadata:
    'SS_cons': <dtype: object>
    'RF': <dtype: object>
Stats:
    sequence count: 433
    position count: 231
-----------------------------------------------------------------------
UUUCUAUCCAGAG-AGG-U-GG----------- ... -------------GCU-UG-A-AA-GAUAGGAA
ACCUUAUUUUGAG-AAG-C-UG----------- ... --------------CU-CG-A-AU-GAUAAGUA
...
AACUUAUCACGAG-CGA-C-CG----------- ... -----------CGCUU-CG-G-AA-GAUAAGGA
GUCUUAUCCAGAG-CAG-C-GG----------- ... ------------UCCG-GG-A-AA-GAUAAGGA
```
Looks fine, but if we look at the ``RA`` metadata tag for example, we will see the data is being stored incorrectly:
```python
>>> msa.metadata['RA']
```
```
Grundy FJ, Henkin TM Winkler WC, Nahvi A, Sudarsan N, Barrick JE, Breaker RR Epshtein V, Mironov AS, Nudler E Rodionov DA, Vitreschak AG, Mironov AA, Gelfand MS Montange RK, Batey RT
```
Instead of seeing separate authors, ``RA`` holds all the authors as one long, ugly string. This is because reference tags are being treated as default ``GF`` tags, and every time the reader sees another ``RA`` tag, it just appends its metadata to the string, as seen above. Additionally as an example, the ``RN`` tag, which should store the Reference Number(s), is simply a string:
```
'[1] [2] [3] [4] [5]'
```

I know this issue is a bit of a read, but this is all the info on the subject. 

Any input is greatly appreciated!

**Comment by jakereps** [comment]
It looks like [`skbio.io.format.stockholm.add_gf_metadata`](https://github.com/biocore/scikit-bio/blob/779750e3adbbe98e6ab0c56bbf5a622f414002ba/skbio/io/format/stockholm.py#L461) is handling a few special cases and then everything outside of those cases is either being created as a string, or if the feature already exists it is concatenating the new data onto the existing data, resulting in a single string of all of the data. It looks like all of the `R_` data, or really all of the `GF` data that isn't handled in the special cases, is currently being concatenated into a single string.

To resolve this you could switch them to be stored as lists and append every new chunk of `feature_data`, but as seen in this example from your post:

```
#=GF RN   [4]
#=GF RM   15215334
#=GF RT   Comparative genomics of the methionine metabolism in Gram-positive
#=GF RT   bacteria: a variety of regulatory systems.
#=GF RA   Rodionov DA, Vitreschak AG, Mironov AA, Gelfand MS
#=GF RL   Nucleic Acids Res 2004;32:3340-3353.
```

Some single blocks of data have multiple lines of the same feature (specifically `RT` in this example), so appending onto a list would cause what was meant to be a single element of feature_data to be broken into multiple elements, so in order for lists to work you would also have to implement some sort of marker in the metadata addition to know which element of that feature you are working with. This is all assuming they are wanting to be accessed as separate items in a list though.

**Comment by Kleptobismol** [comment]
Thanks for commenting @jakereps, yes that is exactly what is happening. 

That's a good idea for storing this data, I'm thinking it's going to have to be something similar to the way we store trees, documented [here](http://scikit-bio.org/docs/latest/generated/skbio.io.format.stockholm.html#module-skbio.io.format.stockholm).

Maybe some sort of nested ``OrderedDict``?

**Comment by jakereps** [comment]
I'm not familiar enough with how these are used to speculate on which way is the best way, but they could either be stored as each Reference in a single object with each `RN` as the key, or keep them all as their separate `RN`, `RM`, etc... keys with the `RN` being the key to the data for each, so something along the lines of:

 `msa.metadata['REFS']['[1]']['RA'] // this seems pretty heavy`
```python
metadata = {
    'REFS': {
        '[1]': {
            'RM': '10094622',
            'RT': 'The S box regulon: a new global transcription termination control system for methionine and cysteine biosynthesis genes in gram-positive bacteria.',
            'RA': 'Grundy FJ, Henkin TM',
            'RL': 'Mol Microbiol 1998;30:737-749.'
        }
    }
}
```
`msa.metadata['RA']['[1]']`  
```python
metadata = {
    'RN': ['[1]', '[2]'],
    'RM': {
        '[1]': '15215334',
        '[2]': ...
    },
    'RT': {
        '[1]': 'Comparative genomics of the methionine metabolism in Gram-positive bacteria: a variety of regulatory systems.',
        '[2]': ...
    },
    'RA': {
        '[1]': 'Rodionov DA, Vitreschak AG, Mironov AA, Gelfand MS',
        '[2]': ...
    },
    'RL': {
        '[1]': 'Nucleic Acids Res 2004;32:3340-3353.',
        '[2]': ...
    },
}

```

**Comment by jairideout** [comment]
Thanks for the discussion on this @Kleptobismol and @jakereps!

Since the reference number isn't all that useful (it just assigns an increasing number to each reference), we could store the references as a list of dicts (`OrderedDict` shouldn't be necessary here since the list maintains order for us). By storing the references in a list, users can access each reference by index position (basically the reference number, just 0-based indexing instead of 1-based). I think this will be more natural/Pythonic than accessing data by RN key (e.g., `[1]`, `[2]`). Something like:

```python
msa.metadata = {
    'RN': [
        {'RM': '10094622', 'RA': 'Grundy FJ, Henkin TM', ...},
        {'RM': '12910260', 'RL': 'Nat Struct Biol 2003;10:701-707.', ...},
        ...
    ]
}

msa.metadata['RN'][0] # access the first reference
msa.metadata['RN'][1] # access the second reference
```

This structure is basically an inversion of @jakereps structure above. I like this a little better because it keeps all the data about a reference in a single `dict`, making it easier to retrieve that info in a single command.

We could use a different tag than `'RN'` to store the list of references, but it seems safer to use `'RN'` since we know that it is a reserved tag with special meaning. If we use a different tag, e.g. `'REFS'`, that could overwrite data if the Stockholm file happens to have the tag `'REFS'` pointing to something else (remember that these tags are arbitrary).

What do you guys think about this structure?

**Comment by Kleptobismol** [comment]
This sounds great, @jairideout! I think it's a good idea to store the data under the ``RN`` tag, because that way when they index in like this: 
```python
msa.metadata['RN'][0]
```
it will be like you are pointing from metadata --> **R**eference **N**umbers --> reference number, which seems intuitive for the user.

**Comment by jakereps** [comment]
Oh, nice. Yeah that's definitely cleaner, @jairideout. I wasn't sure if the `RN` was being used somewhere else in the data, so was trying to hold onto it, but a pure list instead of `...['[1]']` is much easier to use. So for the single reference, but multiline feature data concatenation, you could just hold onto the `RN` you're currently at until either hitting a new reference number, or hitting something that doesn't start with `R`, or would it have to be more universal than that?

**Comment by Kleptobismol** [comment]
Well, the reference number is always stored under the ``RN`` tag, so any time the parser sees that, it will append a new dictionary to the list. Additionally, the dictionary will initially populate with empty strings, so anytime it sees a tag, for example ``RM``, it will simply add it like this: 
If the ``RM`` tag was seen and stored in ``feature_tag``, and its data in ``feature_data``:
```python
self._metadata['RN'][-1][feature_tag] += feature_data
```

**Comment by squirrelo** [comment]
I really like the `['RN'][0] == {'RM': '0000000000', ...}` idea, as it seems the cleanest of all proposed, and easiest to program.  From [wikipedia](https://en.wikipedia.org/wiki/Stockholm_format) it looks like only reference tags start with R, but that might not be a safe assumption in the future.

**Comment by ebolyen** [comment]
Regarding the top-level key, are there any symbols excluded by Stockholm we could use? I like the concept of `refs` or something like that a bit better than `RN`, but `RN` is a safe fallback I suppose.

**Comment by Kleptobismol** [comment]
I think using ``RN`` is a safe bet, especially since the index of the list sort of becomes the Reference Number.

**Comment by jakereps** [comment]
@Kleptobismol if you padded the 0 index of the list upon creation, with either an empty string or a counter of total ref fences, then they could all match exactly as the index from the input, and could avoid any translation confusion between the 1 based RN and a 0 based Python list. Or is this mostly used by programmers where using 0 to get the `[1]` would make more sense?

**Comment by jakereps** [comment]
@ebolyen I can definitely see where a refactor like this could make it strange to lump everything under the `RN` tag, where typing `metadata['RN']` would dump all of the references and their data instead of just the reference numbers, and using `refs` or something similar as the top level could help with the readability.

**Comment by Kleptobismol** [comment]
@jakereps the reference number appears to only be a numbering on a list of references, not a unique id. I think the only reason it exists is to clearly separate the references in the Stockholm file. So, I don't think it matters to hold on to that data, it appears the only thing that needs to be maintained is the order.

**Comment by ebolyen** [comment]
Agree with @Kleptobismol, padding the list would also make the list far harder to deal with (polymorphic vs monomorphic). It is also very likely the the user doesn't have a particular reference they are interested in, if they knew, they would already have the data... so just collecting them together in an iterable should be more than sufficient.

Still feels strange to call it `RN` though:
```python
reference_number = 0
msa.metadata['RN'][reference_number]
```
vs
```python
ms.metadata['references'][reference_number]
```

**Comment by Kleptobismol** [comment]
In order to be sure the tag doesn't interfere with other tags, we could name it something more unique, like ``collected_references`` or something. Thoughts?

**Comment by jairideout** [comment]
I agree it'd be ideal to store the references under a key with a more descriptive name. Stockholm doesn't have any exclusions to tag names except that they can't contain whitespace, so we could safely use a key that has whitespace (e.g., `msa.metadata['reference list']`). Having a key name with spaces in it seems likely to frustrate users, and it would be difficult to come up with an intuitive multi-word name for "references", so I'm not too keen on this solution.

I agree it's a little odd to store the references under the `'RN'` tag, but it's probably the most likely place a user would look for references since we can't use a reasonable name (e.g., `'references'`). Storing references under the "magic" tag `'RN'` is also consistent with how we are storing trees under the "magic" tag `'NH'`. A `'trees'` tag might be more descriptive/intuitive but we are again limited by how arbitrary Stockholm files can be.

**Comment by RNAer** [comment]
instead of creating arbitrary keywords, what about just store all those text as a string and let users process it whatever they like?

**Comment by jairideout** [comment]
Can you post an example of how the data would be stored?

**Comment by RNAer** [comment]
like the following, since in most cases, users don't need to do any compute on references, so it probably fine to just store them unparsed.

```
seq.metadata['reference'] = '''#=GF RN   [1]
#=GF RM   10094622
#=GF RT   The S box regulon: a new global transcription termination control system
#=GF RT   for methionine and cysteine biosynthesis genes in gram-positive bacteria.
#=GF RA   Grundy FJ, Henkin TM
#=GF RL   Mol Microbiol 1998;30:737-749.
#=GF RN   [2]
#=GF RM   12910260
#=GF RT   An mRNA structure that controls gene expression by binding
#=GF RT   S-adenosylmethionine.
#=GF RA   Winkler WC, Nahvi A, Sudarsan N, Barrick JE, Breaker RR
#=GF RL   Nat Struct Biol 2003;10:701-707.'''

**Comment by jairideout** [comment]
As discussed above, we can't define a `'references'` tag because Stockholm files are composed of arbitrary tags that could include `'references'` (namespace conflict). Also, storing the references unparsed differs from how other Stockholm tags are stored in `.metadata`/`.positional_metadata` (see [scikit-bio Stockholm docs](http://scikit-bio.org/docs/latest/generated/skbio.io.format.stockholm.html) for examples).

**Comment by RNAer** [comment]
right, we can change `reference` for other keyword. My point is not to parse it. Just MHO.

**Comment by jairideout** [comment]
Regardless of what name we pick for the key, it could have a namespace conflict because of how general the Stockholm format is. The issue isn't specifically with the name `'references'`. I don't think it's a good idea to leave the references unparsed because it is inconsistent with how other tags are handled and will likely be unexpected to users.

Are there any objections to storing a list of parsed references under the `'RN'` key? Based on the discussion in this thread, it seems to be a good compromise because the references can be parsed, and there is no tag namespace conflict because `'RN'` has special meaning in Stockholm.

**Comment by ebolyen** [comment]
:+1:

**Comment by Kleptobismol** [comment]
👍

**Comment by jairideout** [comment]
Marking this API proposal as accepted, supporting issue is #1348.
