### ISSUE TITLE
Large regression on master

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio#1361]
In the process of getting our benchmarking pipeline up and running, I noticed there was apparently a large regression (4x-5x performance loss across about half our current benchmarks) introduced on master starting at commit [`f9016283`](https://github.com/biocore/scikit-bio/commit/f9016283638ef49ffccb3bb5f79e5a421462cfd1). asv plots can be examined [here](https://s3-us-west-2.amazonaws.com/scikit-bio.org/benchmarks/master/index.html).

**Comment by jairideout** [comment]
Nice catch! I confirmed the large runtime regressions locally. Even after the pandas 0.18.0 RangeIndex update (commit [here](https://github.com/biocore/scikit-bio/commit/87d577a1ba30215cac508d6496b45fbfefd9347e)), there is still a large enough performance hit that this needs to be fixed before release. We were prepared to take a small memory hit when merging [`f9016283`](https://github.com/biocore/scikit-bio/commit/f9016283638ef49ffccb3bb5f79e5a421462cfd1) but didn't account for this runtime hit.

The issue is that creating an empty `DataFrame` (regardless of size) takes ~190 microseconds. This slows down `Sequence` construction when no metadata is present, so this performance hit propagates to *a lot* of `Sequence` methods and things that use `Sequence`. For a startling example, `Sequence` kmer methods are now ~26x slower because lots of `Sequence` objects are being constructed. Even though this performance bug only affects `Sequence` objects *without* metadata, it's a relatively common case. For example, when reading a FASTA file without a QUAL file, you get `Sequence` objects without `positional_metadata`. Thus, this performance bug is likely to be noticed by users.

Reverting [`f9016283`](https://github.com/biocore/scikit-bio/commit/f9016283638ef49ffccb3bb5f79e5a421462cfd1) is not trivial as other updates have been made to that code, resulting in many merge conflicts. Additionally, that merge commit has other changes we want to keep in the codebase, so it'd be a manual, time-consuming process to revert. Reverting will only exacerbate the original motivation for removing the "empty metadata" optimizations once `IntervalMetadata` exists on `Sequence`. The previous optimization simply does not scale because any method on any object that handles metadata needs to carefully use the optimization guards `has_metadata`/`has_positional_metadata`, leading to fragile code that requires careful review to prevent hidden performance bugs. Further, each method needs a corresponding unit test that tests private state to make sure these performance bugs don't exist.

After talking with @gregcaporaso and @ebolyen, we have the following plan. Instead of reverting, missing/empty metadata will be stored as `None`, both internally and at the public API level. This avoids the need for `has_metadata`/`has_positional_metadata` optimization guards, private state unit tests, and hidden performance bugs. It reduces cognitive load for scikit-bio devs and reviewers because you can access metadata publicly or privately and get the same object back. It reduces cognitive load on users because checking for metadata simply becomes `obj.metadata is None`, which is more Pythonic than a special `has_metadata` method. Further, it removes the ambiguity of what makes metadata "empty" or "not present". We even had conflicting definitions of what makes a `DataFrame` "empty" (is it lack of index, columns, or index OR columns?) and `has_positional_metadata` doesn't match `DataFrame.empty`. Using `None` as the null/missing value avoids this mess entirely and fixes the performance regression.

This will introduce a backward-incompatible change to stable API. It will affect users who access `.metadata` or `.positional_metadata` (the public attribute *getter* only) where no metadata was previously provided to the object. Previously, they'd receive an empty dict or DataFrame, now they will receive `None`. In practice this should only affect users who were expecting an "empty" metadata object, likely to mutate further in application code. Now users will receive a `NoneType` error if trying similar operations on `None`. Again, this will only affect users who are manipulating empty/missing metadata. To help developers update their code, we will provide methods to obtain "empty" metadata, which can then be manipulated as usual in application code and added back to the object with metadata setters.

An example should make this clearer:

Previous API:

```python
seq = Sequence('ACGT')
seq.metadata # empty dict, {}
seq.metadata['foo'] = 'bar'
```

New API:

```python
seq = Sequence('ACGT')
seq.metadata # None
seq.metadata = {}
seq.metadata['foo'] = 'bar'
```

While breaking stable API is highly undesirable, we would rather do this over reverting for the reasons described above. Another option is to have a special scikit-bio import that monkey-patches the metadata getters to use the new API (and the old API raises a warning). While this would avoid breaking stable API, all (or nearly all) application developers would be forced to update their code to use this new import and API, and if they don't do this, they could be impacted by the performance bug. It also isn't guaranteed that application developers will notice the warning telling them to update their code, so it seems better to have this breaking change (for some application devs) over the risk of introducing serious performance bugs.

Since this is a backwards-incompatible stable API change, we plan to put together a concise guide to help devs transition their code to the new API. We'll tweet/gitter about this upcoming change before the release and try our best to notify packages using scikit-bio (e.g. using Depsy to figure that out).

If anyone actually read this far and has questions/comments/concerns, please get in touch!

**Comment by ebolyen** [comment]
Thanks for the detailed write-up @jairideout!

**Comment by jairideout** [comment]
After more discussion with @gregcaporaso and @ebolyen, we decided to reinstate the empty/missing metadata optimizations that were removed in #1321. We decided to revert for the following reasons:

- avoid breaking stable public API
- the current API is convenient for users because they don't have to check whether metadata is `None` before doing something with it
- private-state unit tests will exist only for the metadata mixin classes (where that private state is defined). Instead of writing unit tests that test private state to ensure the performance of a method, users and developers are encouraged to submit ASV benchmarks if a method is determined to have suboptimal performance when handling missing/empty metadata. If the missing metadata guards `has_metadata` and `has_positional_metadata` aren't used and this isn't caught during review, the results should still be correct. If performance of the method becomes an issue, it can be addressed and benchmarked with ASV. This separates performance tests from unit (functional) tests and encourages the development of new benchmarks.

PR #1373 implements what I've described here.
