### ISSUE TITLE
ancom reject column is misleading 

### ISSUE THREAD

**Issue by antgonza** [biocore/scikit-bio#1375]
Currently, "significant" values are True in the reject column, perhaps the column should be called "significant" or invert the values so False are those that shouldn't be rejected ...

**Comment by gregcaporaso** [comment]
We wouldn't want to invert the values and keep the column name, as it's implying that the null hypothesis is rejected, but I agree that it's not the most intuitive (and the docs aren't super clear on it). I also hesitate to call it *significant* since we don't have a p-value (which bugs me a little about the method, and I think we're going to field a lot of questions about that). 

What if it were called *Differentially abundant*, and have values of True or False (so True would indicate the feature is differentially abundant, the opposite of how it works now). This would be good to do for 0.5.0, since it is a pretty serious API change, so better to do sooner than later, and especially before it gets used in QIIME 2. I can fix this as part of #1374.

**Comment by antgonza** [comment]
👍

**Comment by gregcaporaso** [comment]
@mortonjt, what do you think about this change?

**Comment by jairideout** [comment]
Is it possible to report the actual p-values instead? `ancom` take `alpha` as input and uses that to determine significance. What if we remove the `alpha` parameter and let the user decide what's significant?

**Comment by gregcaporaso** [comment]
I don't think so, unfortunately. See the content from @mortonjt on my pr.

Sent from my phone, please excuse typos and brevity.

Is it possible to report the actual p-values instead? ancom take alpha as
input and uses that to determine significance. What if we remove the alpha
parameter and let the user decide what's significant?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/biocore/scikit-bio/issues/1375#issuecomment-224628273>,
or mute the thread
<https://github.com/notifications/unsubscribe/AALvdNu5SgbjJow8ZzusIPGvgZ4xz0Qvks5qJuEigaJpZM4IwlAp>
.

**Comment by mortonjt** [comment]
I actually don't see why this has to change. This is standard statistical
terminology. If you look at the modules in statsmodels, this is commonly
used.

And I don't like differentially abundant. It implied that there is an
increase.

I'm ok with updating the docs to make this clear. I don't think this column
should change.

**Comment by rob-knight** [comment]
Differentially abundant does not imply increase, just difference.

On Jun 8, 2016, at 9:10 AM, Jamie Morton <notifications@github.com> wrote:

I actually don't see why this has to change. This is standard statistical
terminology. If you look at the modules in statsmodels, this is commonly
used.

And I don't like differentially abundant. It implied that there is an
increase.

I'm ok with updating the docs to make this clear. I don't think this column
should change.
On Jun 8, 2016 7:01 AM, "Greg Caporaso" <notifications@github.com> wrote:

> @mortonjt <https://github.com/mortonjt>, what do you think about this
> change?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/scikit-bio/issues/1375#issuecomment-224598109
>,
> or mute the thread
> <
https://github.com/notifications/unsubscribe/AD_a3S7o1ga1D8dHzWnv4R0boss7WBvEks5qJssdgaJpZM4IwlAp
>
> .
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/biocore/scikit-bio/issues/1375#issuecomment-224641837>,
or mute the thread
<https://github.com/notifications/unsubscribe/AB69KVOE5ESG0O_sbT-4ADuuqtc2hcFdks5qJumRgaJpZM4IwlAp>
.

**Comment by cuttlefishh** [comment]
I think @mortonjt is right that "reject" is the correct terminology. It should stay as it is, perhaps with some improved documentation.

**Comment by jwdebelius** [comment]
I agree with @cuttlefishh. This is terminology is used elsewhere and draws on the idea that in statistics you "reject the null hypothesis" because you can never say the alternative hypothesis is true for samples... That kind of terminology is widely used in stats textbooks and other avaliable resources.

**Comment by antgonza** [comment]
That's a good point, what about naming the column: reject_null_hypothesis?

**Comment by gregcaporaso** [comment]
I guess the other piece of this is what's more intuitive from a user's perspective. In QIIME, I'd see us wanting to do something with the features that are differentially abundant (report them, return them to a user, ...). If those are the values that are indicated as ``True``, the code that processes that is slightly simpler and I'd argue a lot more intuitive (e.g., @antgonza was initially confused by this). 

Also, if someone tells you the null hypothesis was rejected, don't you usually want to know the p-value? 

I'm still in favor of the change that I suggested, but will go with the majority opinion on this.

**Comment by gregcaporaso** [comment]
I'm going to go with *Reject null hypothesis* for this column name since that seems to be the popular opinion, but I do think *Differentially abundant* would be more clear for our users.

**Comment by mortonjt** [comment]
Keep in mind that `reject` is the parameter being used for statsmodels.  I'd check out statsmodels.sandbox.stats.multicomp.multipletests for an example.

We already stated in the documentation that `reject` is for rejecting the null hypothesis.  And it seems that the misunderstanding here is not because of poor naming.  Its mis-understanding exactly what this test is doing - changing the column name won't change that.

Here's what I recommend - keep the column name as is.  In the documentation, state something as follows

```python
    '''
    Returns
    -------
    pd.DataFrame
        A table of features, their W-statistics and whether the null hypothesis
        is rejected.
        `"W"` is the W-statistic, or number of features that a single feature
        is tested to be significantly different against.
        `"reject"` indicates if feature is significantly different or not.  
        If `True`, then that feature is estimated to be differentially abundant.
        Otherwise, that feature is determined not to change substantially across groups.
     '''
```

Can we agree on this solution?

**Comment by mortonjt** [comment]
Just talked to @antgonza offline , and I think I better understand where the confusion is coming from.

I think `reject_null_hypothesis` is a fine name.  But I still think that the documentation should be updated as noted above.

**Comment by gregcaporaso** [comment]
Thanks, and sounds like we're good on the modified documentation (looks like we converged on that wording).
