### ISSUE TITLE
Does scikit-bio work on windows 10 currently?

### ISSUE THREAD

**Issue by matt-erhart** [biocore/scikit-bio#1382]
Which linux distros are known to work? I may just virtual box my way around this today.

**Comment by mortonjt** [comment]
It should just work on linux.  It has been tested on multiple distros
(Ubuntu, mint, Redhat, ...)

**Comment by jairideout** [comment]
scikit-bio does not currently work on Windows. We're planning to add Windows support during the code sprints at the end of the SciPy conference in July. In the meantime, scikit-bio should work on a variety of linux distros and OS X (let us know if you run into issues and we'll do our best to help).

**Comment by matt-erhart** [comment]
Worked on Mint, thanks. Feel free to ping me if you want a windows tester later this summer.

**Comment by jairideout** [comment]
Awesome, thanks @matt-erhart!

**Comment by MattDMo** [comment]
Has there been any update to this issue since the proposed code sprints last summer? I'm interested in Windows compatibility, specifically Win10.

**Comment by jairideout** [comment]
@MattDMo Thanks for following up! We haven't started working on Windows support yet. We'd appreciate community contributions if you or anyone else is interested in working on this, and we're happy to help in whatever way we can on our end.

**Comment by MattDMo** [comment]
I primarily develop on Linux and OS X, but my work laptop is Win10 (I'm a lab scientist during the day, and a nerd at night), which is why I'm wondering. Unfortunately, with it being a work laptop, I don't have a lot of say in being able to install the MSVC++ development tool chain (and, honestly, I don't have a lot of experience with it anyways), so while I'd be happy to test as an end-user, I'm afraid I can't be of much assistance on the development end at the moment.

Thanks for getting back to me, though!

**Comment by jairideout** [comment]
Great, thanks for offering to test it out! If anyone is interested in working on this please get in touch.

**Comment by mortonjt** [comment]
This should not be a problem with the ubuntu emulators.  Reopen if this has not been addressed
