### ISSUE TITLE
No module named 'skbio.stats.__subsample'

### ISSUE THREAD

**Issue by sowe9385** [biocore/scikit-bio#1391]
Tried installing scikit-bio using both pip and conda.  "Successfully built scikit-bio".  However, error message upon running tests:
pip install scikit-bio
python -m skbio.test
/Users/sophie/miniconda3/bin/python: Error while finding spec for 'skbio.test' (<class 'ImportError'>: No module named 'skbio.stats.__subsample')

I noticed that in skbio.stats there is only _subsample.py not __subsample.py - does the extra _ have anything to do with it?  Thanks!

**Comment by jairideout** [comment]
@sowe9385, are you running `python -m skbio.test` in the scikit-bio source directory (e.g. obtained from a `git clone`)? I wonder if the test command is using the source `skbio` package in your current directory instead of the release-installed package. Can you try changing directories to a different location (e.g., your home directory) and rerunning `python -m skbio.test`?

**Comment by sowe9385** [comment]
I get the same error in my home directory as well as in the scikit-bio source directory (from git clone).

**Comment by jairideout** [comment]
Hmmm that's odd. Can you uninstall scikit-bio completely (both pip and conda installs), and try reinstalling with conda? That's the recommended / easiest way to install scikit-bio and its dependencies, so let's troubleshoot that install method.

If you're having the same issue after reinstalling with conda, can you please post the exact commands you ran (and their output) to create the conda environment and install scikit-bio?

**Comment by sowe9385** [comment]
That worked!  Thank you!

**Comment by jairideout** [comment]
Great, glad to hear a reinstall fixed the issue!
