### ISSUE TITLE
Current version fails to compile on linux with pip

### ISSUE THREAD

**Issue by andersgs** [biocore/scikit-bio#1428]
Just `pip3 install scikit-bio` fails to install. 

Downloading the release version, updating the `setup.py` to include the `numpy `dirs in the Extension portion, and `export USE_CYTHON=True` allowed me to install it locally.

It seems to hang up on installing from '.c' extensions (i.e., when it does not find a `USE_CYTHON` env variable).  The fault seems to lie with the `alignment` extension.

My new `setup.py` extensions section now looks like this:

```
extensions = [
    Extension("skbio.stats.__subsample",
              ["skbio/stats/__subsample" + ext],
                include_dirs = [np.get_include()]),
    Extension("skbio.alignment._ssw_wrapper",
              ["skbio/alignment/_ssw_wrapper" + ext,
               "skbio/alignment/_lib/ssw.c"],
              extra_compile_args=ssw_extra_compile_args,
                include_dirs = [np.get_include()]),
    Extension("skbio.diversity._phylogenetic",
              ["skbio/diversity/_phylogenetic" + ext], 
               include_dirs = [np.get_include()])
]
```

Which, I have since realised that the current `master` branch has as well.

Anders.

**Comment by jairideout** [comment]
Thanks for reporting this issue and your fix @andersgs! This was an issue on OS X El Capitan, reported in #1407 and fixed in #1408. It has since been fixed in master and will be available in the next release. For users encountering this issue with the current release, another alternative is to use `conda` to install scikit-bio (see http://scikit-bio.org/ for details).
