### ISSUE TITLE
skbio.TreeNode does not handle underscores well in node.name

### ISSUE THREAD

**Issue by JTFouquier** [biocore/scikit-bio#1484]
Hi there!

I'm working with a large newick tree that has taxonomy lines (such as: Bacteria_Proteobacteria_Betaproteobacteria_Rhodocyclales_Rhodocyclaceae) instead of accession numbers. I wanted to make a small test tree so I used tree.shear and noticed it does not work with underscores in the name. 

From the example in the docs, I added underscores to the node name. 

I'm using skbio 5.1 and Python 3.5.2

```
import skbio
tree = skbio.TreeNode.read(['((H_bacteria:1,G_bacteria:1):2,(R_bacteria:0.5,M_bacteria:0.7):3);'])
sheared = tree.shear(['G_bacteria', 'M_bacteria'])
print(sheared)
```
which gives the Traceback:

```
Traceback (most recent call last):
  File "shear_hug_tree.py", line 6, in <module>
    sheared = tree.shear(['G_bacteria', 'M_bacteria'])
  File "/Users/jenniferfouquier/miniconda3/lib/python3.5/site-packages/skbio/tree/_tree.py", line 454, in shear
    raise ValueError("ids are not a subset of the tree.")
ValueError: ids are not a subset of the tree.
```

Is there a short fix for this?  Thoughts?

Also, I would really like to use tree.shear but it says that it is experimental as of 4.0. Can I have clarification on what this means in this case? I couldn't find it in the change log. Thanks!

**Comment by jairideout** [comment]
See the scikit-bio [Newick format docs](http://scikit-bio.org/docs/latest/generated/skbio.io.format.newick.html) for how underscores in labels are handled when reading/writing. Briefly: if they are unescaped (which yours are), they are converted to spaces when reading, and there's a `convert_underscores` option to change this behavior. Your `TreeNode.shear` error is happening because the node names no longer contain underscores after the Newick file has been read, so the requested IDs cannot be found.

> Also, I would really like to use tree.shear but it says that it is experimental as of 4.0. Can I have clarification on what this means in this case? I couldn't find it in the change log. Thanks!

See http://scikit-bio.org/docs/latest/user/api_stability.html

**Comment by jairideout** [comment]
I'll close this issue, please reopen if my answer didn't solve your issues.

**Comment by JTFouquier** [comment]
Ah, I remember having this issue before but I was looking in TreeNode docs for clarification. Now that I made myself a workaround. ha. Thank you!
