### ISSUE TITLE
wrong int dtype for subsample_counts

### ISSUE THREAD

**Issue by campenr** [biocore/scikit-bio#1500]
I am trying to use the subsample_counts function and I am getting errors about the integer type using the following code:

```
# using scikit-bio 0.5.1
# using numpy 1.11.3
import numpy as np
from skbio.stats import subsample_counts

matrix = np.array([1, 10, 100, 1000, 10000, 100000])
subsample_counts(counts=matrix, n=5000)
```

This raises 

```
    244         else:
    245             result = _subsample_counts_without_replacement(counts, n,
--> 246                                                            counts_sum)
    247     return result

skbio/stats/__subsample.pyx in skbio.stats.__subsample._subsample_counts_without_replacement (skbio/stats/__subsample.c:1370)()

ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'long'
```

If I set the dtype of the matrix as 

> matrix = np.array([1, 10, 100, 1000, 10000, 100000]).astype(np.int64)

I get:

```
    226 
    227     counts = np.asarray(counts)
--> 228     counts = counts.astype(int, casting='safe')
    229 
    230     if counts.ndim != 1:

TypeError: Cannot cast array from dtype('int64') to dtype('int32') according to the rule 'safe'
```

Which makes it seem like it wants int32, and not int64_t... but on my setup``np.dtype(ctypes.c_long)`` is ``np.int32``... so it would be casting the array to the wrong type anyways...?

Numpy also does not know of the ``int64_t`` type on my system, which leads me to think maybe the issue lies in the build of numpy in my Anaconda installation... but I don't know.

I am running 64-bit Windows 10, and running the 64-bit Anaconda 4.3.0 version of Python 3.6.0.

Thoughts?

**Comment by jairideout** [comment]
It looks like `np.int_` on 64-bit Windows is int32, where on other 64-bit platforms it is int64 ([source](http://stackoverflow.com/a/36279549/3776794)). I think what's happening is:

1. In your first example, the subsample Cython code likely expects int64, so it isn't happy with C long, which is int32 on your system.

2. In your second example, explicitly passing an int64 array will attempt to downcast to int32 (because we're casting to `np.int_`), which isn't allowed according to the "safe" casting rules in numpy.

The Cython code should likely be relaxed to work with int32 or int64 arrays. Unfortunately I don't know of a workaround to use in the meantime... Note that we don't officially support Windows, so you might be better off using scikit-bio on a 64-bit Linux or Mac.

Thanks for reporting the issue!

**Comment by wasade** [comment]
Very weird. I'm using numpy 1.11.2 and cannot recreate the issue, however one critical between our environments is that I'm using OSX.

Thank you for reporting this -- I'll inquire with some others about getting access to test on a windows machine to see if we can recreate and isolate there, or if the issue is elsewhere.

**Comment by jairideout** [comment]
@wasade, looks like we were writing responses at the same time. Check out my comment for the reason why we're seeing this issue (it is Windows-specific).

**Comment by campenr** [comment]
Oh windows, why do I continue to use you. But seriously, thanks for your responses. I will shift this particular analysis to a linux machine.

**Comment by campenr** [comment]
So I found a workaround which is to set ``replace=True`` as this doesn't use the C implemented ``_subdsample_counts_without_replacement`` where the error was occurring.

**Comment by jairideout** [comment]
Glad that worked for you! Just to note, passing `replace=True` will change the behavior to subsample *with* replacement, where the default behavior is to subsample *without* replacement.

**Comment by campenr** [comment]
Am I right in thinking that the output of both with and without replacement is the same, it just changes whether you are modifying the original data or a copy of it? Or is there more to it than that (and if this is the case, do you possibly have a link to a good resource describing the difference?)

**Comment by jairideout** [comment]
The `replace` parameter toggles between subsampling *with* replacement and subsampling *without* replacement. These two subsampling strategies will produce different results. `replace` does not affect in-place vs. returning a new array of results; the function will *always* return a new array containing the subsampled counts and will *never* mutate the input array in-place.

The subsampling strategies (with or without replacement) are common subsampling techniques in statistics. I don't know of a specific reference but there should be many resources online (e.g. see [this page](https://www.ma.utexas.edu/users/parker/sampling/repl.htm)). Let us know if we can clarify anything after checking out those resources.

**Comment by mortonjt** [comment]
@campenr reopen if your question has not been resolved
