### ISSUE TITLE
[Feature Request] Update ANCOM to ANCOM-BC because it's faster

### ISSUE THREAD

**Issue by jolespin** [biocore/scikit-bio#1820]
Are there plans to update ANCOM to ANCOM-BC in the future? ANCOM takes quite a bit of time especially when it's used on gene expression data and not small OTU/ASV tables. 

https://www.nature.com/articles/s41467-020-17041-7

**Comment by mortonjt** [comment]
FYI, this will be implemented in qiime2. I have a qiime2 plugin [here](https://github.com/mortonjt/q2-ancombc) that will be officially supported in `[q2-composition](https://github.com/qiime2/q2-composition) soon.

**Comment by jolespin** [comment]
Is Scikit-Bio going to be developed in the future or is the push largely towards QIIME2?

**Comment by mortonjt** [comment]
I can't say about scikit-bio future development, but I can say with high confidence that we will not be reimplementing ANCOMBC in scikit-bio

**Comment by antgonza** [comment]
Hello! Just trying to help with the future development question; taken from: https://github.com/biocore/scikit-bio/blob/master/README.rst
"""Important project update (April 2022): scikit-bio is currently in maintenance mode. Due to limited developer bandwidth, we are focusing on keeping scikit-bio up-to-date with Python and Python scientific computing libraries. We plan to do this through two annual releases of scikit-bio. At this time, we have less availability for reviewing or adding new features. We realize that scikit-bio is an important tool for the bioinformatics community, and we hope to transition back to more active development in the future. If you're interested in helping by taking a leadership role in the project, please reach out."""

Hope this helps.
