### ISSUE TITLE
Alignment algorithms in cython

### ISSUE THREAD

**Issue by squirrelo** [biocore/scikit-bio#254]
Anyone up to getting Needleman-Wunsch and Smith-Waterman written in cython? The current all-python versions in pyCogent are super slow and the nwalign package has a severe memory leak issue.

**Comment by anderspitman** [comment]
There's still a comment in the alignment code referring to this issue [here](https://github.com/biocore/scikit-bio/blob/1f3bb5a967fd4e9f3105697d10764105d55da0f0/skbio/alignment/_pairwise.py#L539). Can that comment be removed?

**Comment by gregcaporaso** [comment]
Oops, I think this was accidentally closed. Thanks for catching this @anderspitman!

**Comment by anderspitman** [comment]
No problem. If this is orphaned I may even be able to help out with it. I implemented SW and NW a couple weeks ago as part of Coursera's bioinf algos course, and I was actually about to start working on a Rust version for fun. Working on a C/Cython version would help solidify my understanding.

**Comment by gregcaporaso** [comment]
I don't know if this is orphaned - it may just be behind schedule. @ekopylova, can you give a status update on global alignment going into SSW? 

@anderspitman, there are other C/Cython projects that need some attention, see #370 (which may involve just Cython wrapping of existing software, or more implementation if EBD can't be used with sckit-bio). That could be a great bigger project to work on.

**Comment by ekopylova** [comment]
I looked into the code for SSW and noticed the implementation (based on this [paper](http://www.ncbi.nlm.nih.gov/pubmed/17110365)) used for local alignment (the score never falls below 0) will probably need to be reconsidered/modified for global alignment (the score can be negative). I think the limitations in the SSE2 instruction set allow only unsigned byte integers to used in the 8-bit calculations. So, either we must always divide the register into 8, 16-bit elements (which will be slower than 16 8-bit elements) or figure out some tricks.

@torognes has also written a fast SIMD parallelized Smith-Waterman tool called [Swipe](https://github.com/torognes/swipe), it may be worth looking whether this tool can be updated for global alignment? Otherwise, both Swarm and Vsearch use global alignment, so we could look into that code as well.

Writing an optimized Needleman-Wunsch algorithm can take some time and as that is limited, we should find the most efficient approach to this before proceeding ..

**Comment by jairideout** [comment]
@gregcaporaso #370 points to a release management pull request that was already merged, I don't think this was the issue you were meaning to point to?

**Comment by gregcaporaso** [comment]
Oops, fixed, thanks! I meant #730. That'll teach me to type before :coffee:...

**Comment by anderspitman** [comment]
Definitely sounds like @ekopylova has this well in hand. I'll take a look at #730.

@ekopylova, from glancing over those papers, it sounds like SWIPE is significantly faster than SSW. Can Swarm and Vsearch both be used for stand alone alignment?

**Comment by ekopylova** [comment]
I'm not sure what the performance comparison of swipe (2011) is to SSW (2013) since SSW extends on Farrar's striped SSW algorithm, perhaps @torognes will have a better answer to this and your latter question -- can swarm and/or vsearch be used for stand alone global alignment? That would be fantastic.

**Comment by torognes** [comment]
Both SSW and SWIPE computes local alignment scores. I think the SSW library uses Farrar's approach to quickly align two sequences, while SWIPE will quickly align one sequence to 8 or 16 different target sequences. The latter approach is about three times faster (per alignment matrix cell), somewhat depending on the length of the sequences. The speed difference is due to the complete lack of any dependencies between the alignment matrix cells in SWIPE's case, as well as fewer cache/memory accesses by the processing of four columns (instead of one) in the alignment matrix at a time. So the choice depends a bit on how you will use it; if you align only sequences pairwise or if you perform some kind of search where you usually align one query sequence to several target sequences. 

The approach used for local alignments in SWIPE (see [search7.cc](https://github.com/torognes/swipe/blob/master/search7.cc) and [search16.cc](https://github.com/torognes/swipe/blob/master/search16.cc)) is adapted for global alignments in SWARM (see the [search8.cc](https://github.com/torognes/swarm/blob/master/search8.cc) and [search16.cc](https://github.com/torognes/swarm/blob/master/search16.cc) files) and VSEARCH (see [align_simd.cc](https://github.com/torognes/vsearch/blob/master/src/align_simd.cc)). In both SWARM and VSEARCH the actual alignments (not just the score) is also computed, based on saved backtracking information; this works well for sequences shorter than about 5000bp. The code in VSEARCH is simpler to use because all assembly code is replaced by SIMD intrinsics. The code in VSEARCH also allows for more gap penalty flexibility (specific gap open and extension penalties for query and target, as well as for left, right and interior gaps).

There is no dedicated library available yet for using the SWIPE approach, but we are in the process of making one. The plan is to have it ready in May 2015.

For local alignment searches where the score is never less than zero and most alignments usually obtain a rather low score, it makes sense to initially align sequences with 8-bit magnitude, and then recompute with a larger magnitude if necessary. For global alignments, where scores can be negative as well as positive, scores often needs a larger magnitude than 8 bit considering common scoring systems, the length of sequences etc. I think it makes more sense to start with a 16 bit magnitude with global alignments as we have done in VSEARCH.

**Comment by torognes** [comment]
See the libssa library for a library implementing both global and local alignments using SSE2 or AVX2 with the approach used in SWIPE: https://github.com/RonnySoak/libssa

**Comment by ekopylova** [comment]
thanks @torognes !

**Comment by wasade** [comment]
The README indicates it is AGPLv3 but the license file seems to indicate
GPLv3. Will open an issue there. I believe AGPLv3 is compatible with BSD.

**Comment by gregcaporaso** [comment]
Ah, thanks for checking into it and for bringing it up with them.

**Comment by nbolten** [comment]
There's an MIT-licensed cython implementation of Needleman-Wunsch (and SW) available here that I use regularly: https://github.com/FredrikAppelros/align. It's pretty fast (for Needleman-Wunsch).

**Comment by iosonofabio** [comment]
I have SWIG-wrapped C++ functions from [SeqAn](http://www.seqan.de/) for local and global pairwise alignments in [seqanpy](https://github.com/iosonofabio/seqanpy). The global alignment has three versions:

- no gaps at the edges
- edge gaps only in second sequence
- right edge gap in first sequence, left edge gaps in second sequence (for chaining sequences)

Any interest in this?

**Comment by jairideout** [comment]
@iosonofabio thanks for pointing us to seqanpy! In the coming months @anderspitman will be redesigning the pairwise alignment API in `skbio.alignment` and evaluating existing aligner packages with Python bindings (ideally scikit-bio's alignment API will support more than one aligner backend). Ultimately this will result in a [scikit-bio RFC](https://github.com/biocore/scikit-bio-rfcs) to get input from the community before implementation. We'll be sure to check out seqanpy as part of this!

**Comment by iosonofabio** [comment]
Even if you rewrite the C++ code, please bear in mind the 3 types of global alignments, i.e. their different behaviours w.r.t. gaps at either edge. Thanks!

**Comment by jairideout** [comment]
Thanks for the info @iosonofabio, we will definitely keep that in mind when evaluating aligners and designing the API.

**Comment by gregcaporaso** [comment]
[Parasail](http://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-0930-z) by @jeffdaily looks like it might have what we need, and he explictly mentions interest in making this accessible through scikit-bio in the paper. This looks like a promising option for getting fast global, semi-global, and local aligners in scikit-bio with a consistent interface. (Thanks @GabeAl for sharing this!)

**Comment by iosonofabio** [comment]
@gregcaporaso how far are with this? I am willing to try and give it a go to include parasail bindings into scikit-bio if there is support for that.

**Comment by jairideout** [comment]
@gregcaporaso and I haven't made progress on this. @RNAer or @wasade, any interest in working with @iosonofabio to get this functionality into scikit-bio?

**Comment by RNAer** [comment]
I am certainly happy to review the code

**Comment by jvkersch** [comment]
> Parasail by @jeffdaily looks like it might have what we need, and he explictly mentions interest in making this accessible through scikit-bio in the paper. This looks like a promising option for getting fast global, semi-global, and local aligners in scikit-bio with a consistent interface.

@gregcaporaso @jairideout @RNAer @iosonofabio I have a package with Cython bindings for Parasail at https://github.com/jvkersch/parasail-cython. Assuming you haven't already done this independently, I'd be willing to help port some of this over to scikit-bio.

**Comment by iosonofabio** [comment]
I haven't had time to do this, unfortunately... go for it and thank you!

**Comment by jeffdaily** [comment]
Surprised and happy to see this thread get picked up again years later.  @jvkersch I really appreciated the comment in your README that [parasail-python](https://github.com/jeffdaily/parasail-python) was "excellently-documented".

![achievementunlocked](https://user-images.githubusercontent.com/904248/43207680-71fee30e-8fdd-11e8-85c6-24e3f1787986.png)

[parasail-python](https://github.com/jeffdaily/parasail-python) started out with cython bindings.  Compiling for windows scared me away so I went with ctypes instead.  I provide the [C parasail library](https://github.com/jeffdaily/parasail) on windows using appveyor artifacts and ship/download the DLL as part of the wheel build.  On mac and Linux the C library master branch is downloaded and built.  I use a [hacky python script](https://github.com/jeffdaily/parasail-python/blob/master/tools/ctypesgen2.py) to generate the ctypes wrappers, but it could probably be converted to generate cython.

**Comment by ebolyen** [comment]
Hey all! Really excited to see discussion on this again. `skbio.alignment` isn't in very good shape (and `ssw.c`, as many know, prevent us from compiling on Windows). No real progress has been made in the interim of this issue-thread, so if someone was interested in taking over here, I think they would be a real hero!

One thing that could be really exciting about Parasail would be removing SSW from scikit-bio, which is preventing us from distributing on Windows. If there's Cython bindings, then it sounds like we could be in good shape there!

To the best of my knowledge, @BenKaehler is one of the few users of the SSW bindings in scikit-bio, but I'm pretty sure any equivalent local aligner should be fine. So I would definitely push towards dropping SSW in favor of Parasail. Otherwise, I don't think there's many consumers of it and certainly not enough to justify not supporting Windows.

One thing that's probably worth thinking about is how the API should look, but again, almost anything will be an improvement as no real progress has been made in the `alignment` subpackage (outside of TabularMSA I suppose).

Also something to add to the discussion, our Sequence objects are backed by numpy char arrays, so extracting the underlying ASCII buffer should be really straight-forward.

**Comment by jvkersch** [comment]
@jeffdaily Unfortunately my library is a whole lot less well-documented ;-) In particular, I too started off with a script to autogenerate the wrappers (though I appreciate with hindsight that this could have been done with parasail-python) but I overhauled that to work towards a higher-level API which the readme doesn't yet reflect. My use-case was to have something like a single function `align` that takes two strings and some reasonable defaults, and figures out the rest (or raises a helpful error if it can't do that). I imagine this could be the thing we need in scikit-bio.

**Comment by jvkersch** [comment]
Sounds like there is a good level of interest in this!

1. How do we want to interface with Parasail (the C library)? If we write our own Cython wrappers we have to find a way of vendorizing the Parasail code, or building against a released version and shipping the shared object files. Alternatively, we could put aside the Cython idea for a while and use parasail-python, which uses ctypes and already bundles the dlls as Jeff pointed out. I'd be tempted to choose the latter option since parasail-python is already tried and tested, and we can always switch to Cython later on if necessary.

1. Do we want a new API altogether or do we want to keep the existing API as much as possible but switch out the implementation for one that calls into Parasail? I took a cursory glance at the "slow" algorithms (`global_pairwise_align_*` and `local_pairwise_align_*`) and this seems doable. The current SSW implementation seems to have a few options that Parasail SSW emulation doesn't support, like `mask_length`, but perhaps those can be dropped.

**Comment by ElDeveloper** [comment]
> My use-case was to have something like a single function align that takes two strings and some reasonable defaults, and figures out the rest (or raises a helpful error if it can't do that). I imagine this could be the thing we need in scikit-bio.

Having something along those lines sounds tremendously useful!

Regarding the question about interfacing, I also think using parasail-python would make the most sense (at least at this point). Later on, if this shows promise we could work on improving this.

I like the idea of a single entry point via an `align` interface, it will take finesse to get this right but will likely become a cornerstone of skbio.

**Comment by wasade** [comment]
Wow...

**Comment by jeffdaily** [comment]
Hi -- sorry I didn't realize https://github.com/jeffdaily/parasail-python/issues/24 was still a blocker.  I'll take another look.  I don't have access to a mac anymore so I'll see if I can't verify a fix using travis or by pinging the issue author.

**Comment by tlambert03** [comment]
I’m the author of that Mac parasail issue, also paying close attention to this thread... let me know if I can be of any help!

**Comment by jeffdaily** [comment]
@tlambert03 please re-test https://github.com/jeffdaily/parasail-python/issues/24 with the latest master.

**Comment by tlambert03** [comment]
commented in the parasail thread.  appears fixed at first test.

**Comment by khp1** [comment]
Hello, 
I just wanted to say that I was using the global alignment function from skbio.alignment for clustering my 4000 16S sequences (which are ~253bp long) into OTUs. After letting the code (from here: http://readiab.org/book/0.1.3/2/5#1.4) run for ~24h, it had clustered only about 600 of the 4000 sequences. Then I used the global alignment function from parasail.py by @jvkersch   (https://github.com/jvkersch/scikit-bio/blob/enh/parasail/skbio/alignment/parasail.py) and in less than an 30 min it clustered all 4000 sequences! Thanks to @jvkersch  and could this please be the default method because it scales very well for large datasets?

**Comment by jvkersch** [comment]
@khp1 Thanks for bringing this up. This work stalled mainly because I was striving for drop-in replacements of the existing algorithms, which is probably the wrong way to go about things. I'd be happy to revisit this and provide the Parasail implementations as an extra feature, in addition to the existing implementations, if there is interest.

Out of curiosity, since you're dealing with 16S sequences, have you tried something like `vsearch` for producing OTUs? I am not sure, but it should be able to produce OTUs in well under an hour, especially if you use multiple threads.

**Comment by gregcaporaso** [comment]
Hi @khp1, I agree with @jvkersch's suggestion: vsearch is much better suited for this. We also support that functionality in QIIME 2 through the [q2-vsearch plugin](https://docs.qiime2.org/2020.2/plugins/available/vsearch/). 

You should have received an `EfficiencyWarning` from scikit-bio indicating that runtime is a known issue with this code ([here's](https://github.com/biocore/scikit-bio/blob/0.5.6/skbio/alignment/_pairwise.py#L595) the warning that gets issued).

**Comment by khp1** [comment]
@jvkersch , @gregcaporaso  Yes, I usually use the vsearch tool on qiime 2. But for a couple of reasons that would not have worked for me this time. Also, I like this tool slightly better, because it can tell me how the sequences were clustered (not sure if vsearch does that).

**Comment by cagansevencan** [comment]
Any update on the SSW version of global alignment? It takes pretty long when ran on Google Collab.

**Comment by Midnighter** [comment]
Came here to ask about global alignment, too. I love that scikit-bio provides such a performant local alignment via SSW but need global alignment now. Using BioPython with the emboss command line tool for Needleman-Wunsch is so painful and not very performant either.

**Comment by gregcaporaso** [comment]
@Midnighter, we haven't had any progress on this unfortunately. See [this related issue](https://github.com/biocore/scikit-bio/issues/1814) - in short, we're recommending the [Python bindings for parasail](https://github.com/jeffdaily/parasail-python) for performant alignment algorithm access.

**Comment by Midnighter** [comment]
Fair enough, thank you for the note. In the meantime, I also found these bindings which look very interesting as they provide access to the wave front alignment methods https://github.com/kcleal/pywfa
