### ISSUE TITLE
Port FastUnifrac code to skbio

### ISSUE THREAD

**Issue by josenavas** [biocore/scikit-bio#46]
It can be assigned to me.

Is there any special improvement that we want to explore?

**Comment by gregcaporaso** [comment]
I'm going to port my IAB implementations of PD and UniFrac to skbio next week. These will get an experimental interface in place, and support a benchmark of different implementations.

**Comment by wasade** [comment]
:+1:

I can port fast unifrac sans changes except for removing the cogent dependency. There's some added stuff with the cogent implementation, like doing PCoA, which I wont' bring over -- the goal is minimal, adapt to the pending skbio interface, and remove cogent dep.

**Comment by gregcaporaso** [comment]
I think it makes sense for only one of us to do this, since we don't want multiple implementations in skbio. It doesn't really matter what implementation is ported over since this would just be to get an experimental interface in place, as well as extensive tests that can be easily applied to different implementations. Mine would be really simple to port over so I don't mind taking this on (there are no cogent dependencies, etc, it's just moving code from IAB), but let me know if you'd rather do it. Writing the tests will be the slower part for this, but maybe some of that can come from cogent.

**Comment by wasade** [comment]
Right,  I figured you'd have the interface in place quickly? Or do you only
want to do a slow educational one and delay a production one? Note, the
runtime between the classic unifrac algorithm and fast unifrac are
substantial

**Comment by gregcaporaso** [comment]
Yep, I'll have the ([experimental](http://scikit-bio.org/docs/latest/user/api_stability.html#experimental)) interface and unit tests in next week. Once those are in, we can swap in whatever under the hood based on whichever implementation performs best. I was just going to take my IAB implementation since it already works with skbio so it'll be really quick to get in and we can use that as one of the functions in the benchmark. If it turns out to be slower but intuitively much easier to grasp than whatever implementation we land on, we could have this implementation raise an ``EfficencyWarning`` (i.e., be an "educational" implementation, as with the python aligners) .

**Comment by wasade** [comment]
Yup, that was the plan

**Comment by gregcaporaso** [comment]
Awesome, more soon...

**Comment by jairideout** [comment]
Fixed in #1027.

**Comment by wasade** [comment]
The title of this issue implies it should still be open re: #1040?

**Comment by jairideout** [comment]
Good catch!

**Comment by jairideout** [comment]
Fixed in #1040.
