### ISSUE TITLE
BiologicalSequences.distance can only length check Hamming

### ISSUE THREAD

**Issue by wasade** [biocore/scikit-bio#514]
See [here](https://github.com/biocore/scikit-bio/blob/master/skbio/core/sequence.py#L659) with a discussion in #508. Since it is the responsibility of the distance methods to length check, one possible solution is to try/except on the call to the distance method and thrown an informative error.

**Comment by jairideout** [comment]
Thanks @anderspitman for looking into this!

The scipy fix is in a release (0.15.1), but this only affects Hamming distances. From looking through the other scipy distance metrics, it doesn't look like length-checks are necessarily performed, though each docstring seems to indicate that the input vectors should be of equal length.

I think we could move the length-check [here](https://github.com/biocore/scikit-bio/blob/master/skbio/sequence/_sequence.py#L891) out of the if-statement so that it is executed regardless of what `distance_fn` is provided. That way scikit-bio users will get a descriptive/high-level error message for any distance metric and we don't have to make assumptions about the type of error raised within each scipy distance function (like we would have to in a `try`/`except`). This fix will work with older and future versions of scipy, so we won't have to change our required scipy versions.

@johnchase I think this issue would be a good one for you to get started on. Can I assign this to you?

**Comment by wasade** [comment]
:+1:

**Comment by johnchase** [comment]
@jairideout that sounds good, thanks.
