### ISSUE TITLE
investigate airspeed velocity

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#517]
We saw a talk today by the author of [airspeed velocity](https://github.com/spacetelescope/asv). Would be awesome to get this set up with scikit-bio for benchmarking (time and memory) our code. See astropy's page [here](http://mdboom.github.io/astropy-benchmark/) for an example.

**Comment by anderspitman** [comment]
After investigating `asv` over the last couple days, it's looking pretty good. We still have the following action items:

1. Figure out what tests are going to be added to our benchmarking suite. We discussed possibly generating some of them from our doctests.

2.  Figure out how the benchmarking tests will be maintained. Will it be the responsibility of developers to add/update benchmark tests when they make changes to the public API, or will core developers handle this? Obviously this will be less of a concern as the API stabilizes.

3. Figure out where `asv` and our benchmarking tests will live in git. Should we keep everything in the scikit-bio repo, or create a separate repo? Likely we will want at least the benchmarking tests in the scikit-bio repo, but the results (they exist as json files) probably in a separate repo since they will grow and we don't want our user to have to download the results.

**Comment by johnchase** [comment]
Thanks, @anderspitman I agree about keeping the benchmarks in scikit-bio but the results elsewhere. 

One additional note, due to the import structure of scikit-bio we unfortunately cannot run asv on any commits in the past, however it is currently working and will be moving forward.

**Comment by anderspitman** [comment]
Also see [my issue on the asv tracker](https://github.com/spacetelescope/asv/issues/272).

**Comment by adamrp** [comment]
Last I heard (which was a while ago) there were no hooks for CI (travis,
jenkins, etc.). Being that this is benchmarking, consistent hardware is
important, so settling on a machine and configuration will be important. If
the machine changes, benchmarks run on the new machine won't be directly
comparable to benchmarks run on the previous machine.

**Comment by anderspitman** [comment]
@ebolyen @jairideout @gregcaporaso a couple questions:

1. Do we want to save benchmark results on github? I'm not sure that there's any reason to since they can be regenerated, and if (when) we update benchmarks they will need to be regenerated anyway. So I don't think we need to have anything other than our benchmarks.py and asv.conf.json on github.

2. Assuming you agree with 1, we can probably just add a `benchmarking` at the top level of scikit-bio.

**Comment by gregcaporaso** [comment]
I don't think we need to store the results on GitHub.

**Comment by wasade** [comment]
What about as a post push hook, or a PR service? Would be awesome if these
were just calculated for free but it could also just consume too much time
with travis

**Comment by gregcaporaso** [comment]
That's going to happen, we have a dedicated machine here that we're using to run it. This question is about saving the results.

**Comment by wasade** [comment]
Ah. Small postgres db? Would be great to have for tracking performance over
time

**Comment by gregcaporaso** [comment]
That information will be available, just not stored on GitHub.

**Comment by wasade** [comment]
:+1:

**Comment by anderspitman** [comment]
Yeah asv uses a simple json flat file method for storing results. Our benchmark server can cache prior runs so we only need to run for new commits, but if the data gets wiped out it's not a big deal since we can just go back and re-run everything over the old commits.

**Comment by anderspitman** [comment]
asv is now up and running! We're currently developing the following project which automatically runs asv based on certain Github webhooks events (ie pull requests):

https://github.com/anderspitman/autobencher

This is still in the very early stages but is looking promising so far.

**Comment by jairideout** [comment]
Awesome, thanks for getting this up and running @anderspitman! Closing since we have a working prototype and the `autobencher` repo is tracking remaining to-do items.

**Comment by gregcaporaso** [comment]
This is great news, thanks @anderspitman!
