### ISSUE TITLE
Convert Ordination Classes to Functions

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#829]

**Comment by Jorge-C** [comment]
Just to provide the rationale on why they're classes:
The whole computation consists of two parts, an expensive one that's always necessary and you don't want to keep recomputing, and a cheap one depending on what aspect of the data you want to focus on when visualizing (ie, the scaling you want).

**Comment by jairideout** [comment]
Thanks @Jorge-C, sorry that we missed the `scaling` parameter to the `scores` method. Here's a couple potential solutions (which aren't necessarily mutually exclusive) that might make the API more intuitive for our target users:

- Keep the OO interface so that users interested in different scalings can efficiently compute these. Provide high-level procedural interfaces that simply use the OO interface internally.
- Make the ordination classes callable (`__call__`) instead of a `scores` method. This would make the classes a little more "procedural".

Do you anticipate more methods being added to the ordination classes in the future?

**Comment by mortonjt** [comment]
In the future, I'm planning on adding in some SVD methods.  But they would most likely be tied with the contingency table.  Do you think they would belong in the Ordination classes, or a separate PCA class?

**Comment by ebolyen** [comment]
I'm looking at some of the source code for what scaling does. In some cases it looks trivial, and in others its just a scalar (go figure). I'm not entirely sure how yet, but I feel like we may be able to sidestep this concern entirely with the correct factoring.

**Comment by jairideout** [comment]
Fixed in #925.
