### ISSUE TITLE
Clean up skbio.util

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#833]
`util only exports functions that are useful to the codebase in scikit-bio or is relevant to users within the context of biology but escapes classification otherwise`

- [ ] Remove create_dir
- [x] remove flatten
- [ ] move is_casava_v180_or_later into fastq sniffer
- [ ] remove remove_files

**Comment by jairideout** [comment]
@johnchase are you interested in working on the removal of `flatten`? This function isn't used anywhere in the codebase and can be replaced with a one-liner that's probably faster:

```python
itertools.chain.from_iterable(my_list)
```

See [this SO post](http://stackoverflow.com/q/406121/3776794) for more details.

What we'll want to do is deprecate the function instead of removing it outright and make a note in the changelog. I recommend searching the codebase for `DeprecationWarning` for examples of how we're doing this. [This PR](https://github.com/biocore/scikit-bio/pull/849) removed a bunch of deprecated code, the diff has some good examples of deprecated functionality.

**Comment by johnchase** [comment]
@jairideout yes you can assign this to me.

**Comment by ElDeveloper** [comment]
This function is in use in qiita in a few places, would that not be
enough reason to keep it? Also ... sum(my_list, []) also does the trick
however the readability is immediately reduced.

**Comment by jairideout** [comment]
I recommend moving the function to Qiita. Does that work?

**Comment by ElDeveloper** [comment]
That works ...

**Comment by gregcaporaso** [comment]
Or why not replace with the one-liner that's recommended on SO?

**Comment by jairideout** [comment]
Do you mean replace `flatten`'s implementation in scikit-bio (and keep the function), or update Qiita to use the one-liner?

**Comment by gregcaporaso** [comment]
If there is an easy python idiom to do it, I think we should just use it (so in this case, use the one-liner in Qiita). For example, this is what we're effectively doing when with statements like ``"".join(['A','B','C'])``. I think that's better than writing our own functions to wrap these idioms, and it's clearer for new developers. But, I don't have very strong feelings on which is the better way to go here.

**Comment by jairideout** [comment]
Thanks for clarifying, I like your idea of having Qiita use the idiomatic one-liner and removing `flatten` from scikit-bio to avoid a similar situation to `qiime.util` or `cogent.util`.

**Comment by rob-knight** [comment]
I don't have a strong opinion on this. flatten() is self-evident to new users (which, Greg, is why you previously argued in favor of it when we were merging with Gavin's codebase) but it also dates to 2002, before the one-liner was available. So it may be in same category as s[::-1] rather than dedicated reverse() function.


On Feb 17, 2015, at 3:55 PM, Jai Ram Rideout <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean replace flatten's implementation in scikit-bio (and keep the function), or update Qiita to use the one-liner?

**Comment by gregcaporaso** [comment]
I thought our function may have predated the one liner, but wasn't sure.

**Comment by rob-knight** [comment]
There are a lot of things like that in the codebase, which should be systematically modernized. At the same time, we have to get stuff done, and we saw the issue of too many simultaneously changing dependencies last year with the qiime-pycogent-biom-qiita-pyqi deadlock. So we need to identify reasonable path forward that keeps development fun and productive...


On Feb 17, 2015, at 4:27 PM, Greg Caporaso <notifications@github.com<mailto:notifications@github.com>> wrote:

I thought our function may have predated the one liner, but wasn't sure.

**Comment by gregcaporaso** [comment]
@rob-knight, note that this (and all other backward-incompatible changes) are going into scikit-bio 0.3.0 or later. QIIME/Qiita/etc all depend on scikit-bio < 0.3.0 (the latest release is 0.2.3). This gives us the freedom to address issues like this, while at the same time having the ability to add bug fixes, performance improvements, etc into the scikit-bio 0.2.x branch that can be used by the packages that cannot be delayed by a changing scikit-bio API.
