### ISSUE TITLE
Segmentation fault on nosetests

### ISSUE THREAD

**Issue by vivekiitkgp** [biocore/scikit-bio#861]
Hi,

I cloned scikit-bio and installed as directed in the [README](https://github.com/biocore/scikit-bio#installation-of-development-version). However, on running `nosetests --with-doctest`, I get segmentation fault on one of the tests.

[Here](https://gist.github.com/vivekiitkgp/48c31993f5c0ee1fd8ab) is the gist of the output.

nosetests version 1.3.4

**Comment by ebolyen** [comment]
Can you import skbio from a python interpreter? There is likely something going on with the compiled code.

**Comment by vivekiitkgp** [comment]
Yes. The import is successful.

**Comment by ebolyen** [comment]
What operating system do you use?

**Comment by vivekiitkgp** [comment]
Linux ubuntu 3.13.0-24-generic i686 GNU/Linux

**Comment by ebolyen** [comment]
Where is your python located, and is nosetests using the same one? Assuming you are, try running `pip install -e .` in the root of scikit-bio again.

**Comment by vivekiitkgp** [comment]
Yes. I'm using Python 2.7 and nosetests-2.7 to ensure that same version of
python is being used.

Re-running the command didn't change the output.

**Comment by ebolyen** [comment]
type `which nosetests | xargs less` the top line should be the same location as `which python`

**Comment by vivekiitkgp** [comment]
````
$ which python
/usr/local/bin/python
$ which nosetests-2.7 | xargs less
#!/usr/bin/python
..
````

**Comment by anderspitman** [comment]
@vivekiitkgp are you still running into problems with this?

**Comment by vivekiitkgp** [comment]
@anderspitman Yes. I couldn't resolve it.

**Comment by anderspitman** [comment]
@vivekiitkgp looking at your results from running the commands @ebolyen suggested, it looks like ``nosetests-2.7`` is using a different python interpreter (``/usr/bin/python``) than your shell (``/usr/local/bin/python``). Can you run the same commands with ``nosetests`` instead of ``nosetests-2.7``?

On a side note, I highly recommend using Anaconda or at least virtualenv. Saves a lot of headaches over the system python. Anaconda in particular I've found to be awesome.
