### ISSUE TITLE
Ordination methods restricted to DistanceMatrix

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#869]
Looking at the Ordination methods that we have now, it seems that they can only be used on Distance Matrices.  

This is a bit restrictive, since these Ordination methods cannot be applied to raw abundance tables - which is a necessity for feature ordination (aka reducing feature spaces)

Can we either
1. Add an `apply` method to the DistanceMatrix, DissimilarityMatrix and the Contingency table (once we figured that out)?  This could allow us to make handling these objects ordination agnostic.
2. Get rid of the distance matrix requirement for our existing Ordination classes.

I think it would be really cool to be able to apply these ordination techniques to datasets other than Distance matrices.

**Comment by rob-knight** [comment]
This was intentional as it allows distance matrices calculated with auxiliary information, notably the phylogenetic tree, that is external to the feature table to be used.

In the past (2009-era) when we tested it feature-level ordination was not very useful. However I agree that the scale of data has changed so much since then that it is worth revisiting this, LLE, equation learning, topic modeling, and other techniques that improve with additional data...


On Mar 8, 2015, at 2:20 PM, mortonjt <notifications@github.com<mailto:notifications@github.com>> wrote:


Looking at the Ordination methods that we have now, it seems that they can only be used on Distance Matrices.

This is very restrictive, since these Ordination methods cannot be applied to raw abundance tables - which is a necessity for feature ordination.

Can we add an apply method the DistanceMatrix, DissimilarityMatrix and the Contingency table (once we figured that out)?

This could allow us to make handling these objects ordination agnostic.

**Comment by mortonjt** [comment]
Makes sense!

It is also possible that feature ordination didn't work well in the past because it wasn't analyzed in the proper sample space.   I would be happy to elaborate during our Tuesday meeting.

**Comment by mortonjt** [comment]
Switching gears.

Coming to think of it, eigenvalue decomposition doesn't even work on rectangle matrices.  So having the DistanceMatrix requirement is actually a really good design decision!

On the otherhand, the SVD works just fine on rectangular matrices.  In fact, I would think it would be a bit redundant to apply an SVD on a symmetric square matrix `X`, because `np.dot(X, X.T)==np.dot(X.T, X)`, so you are calculating the same set of eigenvectors twice.

@wasade , do you have any thoughts on this?

**Comment by jairideout** [comment]
@mortonjt out of the 4 available ordination techniques in scikit-bio, only PCoA requires the input to be a `DistanceMatrix` object. The rest accept `array_like`, which can be rectangular matrices representing raw abundance tables. Ultimately this will be integrated with (or replaced by) the `ContingencyTable` object when it is ready, but for now we're using a lower-level data structure (`numpy.ndarray`) to represent this information (similar to scikit-learn).

**Comment by mortonjt** [comment]
Sounds good!
